export const SETCUSTOMSOURCE = 'SETCUSTOMSOURCE';
export const SETMEMBERROLES = 'SETMEMBERROLES';
export const SETMEMBERROLEID = 'SETMEMBERROLEID';
export const SETACTIVITYS = 'SETACTIVITYS';
export const SETDESIGNERS = 'SETDESIGNERS';